In [26]:
import numpy as np

In [27]:
array2=np.array([[1,2,3,4,5],[2,3,4,5,6]])

array2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [28]:
array2.shape

(2, 5)

In [29]:
# arrangining array elements or creating array 
np.arange(0,10,2).reshape((5,1))

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [30]:
# ones function create array of 1
np.ones(4)
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
# eye : creating digonal element as 1
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
arr=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)
print(arr.size)

2
(2, 5)
int32
4
10


In [33]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]


In [34]:
# sqrt
print(np.sqrt(arr2))
# natural log
print(np.log(arr2))
# sin
print(np.sin(arr2))

[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]


In [35]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(arr[0][0])
print(arr[0:])
print(arr[1:])
print("2,3,5,6 only",arr[0:2,1:3])

1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
2,3,5,6 only [[2 3]
 [5 6]]


In [37]:
arr[0][0]=100
print(arr)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [38]:
data=np.array([1,2,3,4,5])

print(np.mean(data))
print(np.round(np.std(data),2))
print("Median",np.median(data))
print("Variance",np.var(data))

3.0
1.41
Median 3.0
Variance 2.0


In [39]:
data=np.array([1,2,3,4,5,6,7,8])
data[(data>=5) & (data<=7)]

array([5, 6, 7])

# Working with pandas



In [40]:
# Series:series is one dimensional array like object that can hold any data type. and it is similler to column
import pandas as pd
data=[1,2,3,4,5,6,7]

series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64


In [41]:
# creating series from dictionary

dict={
    "a":1,
    "b":2,
    "c":3
}

series=pd.Series(dict)
print(series)

a    1
b    2
c    3
dtype: int64


In [42]:
data1=["RIshi","MAhesh","Prabhas","PK","Ravi"]
ind=[1,2,3,4,5]
series_data=pd.Series(data=data1,index=ind)
print(series_data)

1      RIshi
2     MAhesh
3    Prabhas
4         PK
5       Ravi
dtype: object


In [43]:
# Dataframe :have multiple rows and columns 

# creating dataframe

data={
    "Name":["RIshi","MAhesh","Prabhas","PK","Ravi"],
    "Age":[21,40,45,46,49],
    "City":["Pune","Hyedrabad","Hyedrabad","Vishakhapatnam","Hyed."]
    
}

df=pd.DataFrame(data)
print(df)

      Name  Age            City
0    RIshi   21            Pune
1   MAhesh   40       Hyedrabad
2  Prabhas   45       Hyedrabad
3       PK   46  Vishakhapatnam
4     Ravi   49           Hyed.


In [44]:
data=[
    {"Name":"RIshi","Age":21,"city":"pune"},
    {"Name":"RIshi","Age":21,"city":"pune"},
    {"Name":"RIshi","Age":21,"city":"pune"},
    {"Name":"RIshi","Age":21,"city":"pune"}
]

series=pd.DataFrame(data)
print(series)

    Name  Age  city
0  RIshi   21  pune
1  RIshi   21  pune
2  RIshi   21  pune
3  RIshi   21  pune


In [45]:
df=pd.read_csv('Churn_Modelling.csv')
print(df.head(5))

FileNotFoundError: [Errno 2] No such file or directory: 'Churn_Modelling.csv'

In [ ]:
df['Exited'].head(5)

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [ ]:
df.loc[1]

RowNumber                  2
CustomerId          15647311
Surname                 Hill
CreditScore              608
Geography              Spain
Gender                Female
Age                       41
Tenure                     1
Balance             83807.86
NumOfProducts              1
HasCrCard                  0
IsActiveMember             1
EstimatedSalary    112542.58
Exited                     0
Name: 1, dtype: object

In [ ]:
# Accessing specified element
df.at[3,'RowNumber']

4

In [ ]:
# Accesiing specified element iat means index at
df.iat[2,2]

'Onio'

In [ ]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
# Data Manipulation with dataframe
data={
    "Name":["RIshi","MAhesh","Prabhas","PK","Ravi"],
    "Age":[21,40,45,46,49],
    "City":["Pune","Hyedrabad","Hyedrabad","Vishakhapatnam","Hyed."]
    
}

df=pd.DataFrame(data)
print(df)

      Name  Age            City
0    RIshi   21            Pune
1   MAhesh   40       Hyedrabad
2  Prabhas   45       Hyedrabad
3       PK   46  Vishakhapatnam
4     Ravi   49           Hyed.


In [ ]:
df['Salary']=[40000,50000,60000,35000,40000]

In [ ]:
df

Name  Age            City  Salary
0    RIshi   21            Pune   40000
1   MAhesh   40       Hyedrabad   50000
2  Prabhas   45       Hyedrabad   60000
3       PK   46  Vishakhapatnam   35000
4     Ravi   49           Hyed.   40000

In [ ]:
df.drop(columns='Salary',axis=1,inplace=True)
# By default drop has axis 0 for row means it will check in row and axis is 1 means it will check in column


In [ ]:
df

Name  Age            City
0    RIshi   21            Pune
1   MAhesh   40       Hyedrabad
2  Prabhas   45       Hyedrabad
3       PK   46  Vishakhapatnam
4     Ravi   49           Hyed.

In [ ]:
df['Age']=df['Age']+1
df

Name  Age            City
0    RIshi   22            Pune
1   MAhesh   41       Hyedrabad
2  Prabhas   46       Hyedrabad
3       PK   47  Vishakhapatnam
4     Ravi   50           Hyed.

In [ ]:
# for dropind row give row index 
df.drop(4)

Name  Age            City
0    RIshi   22            Pune
1   MAhesh   41       Hyedrabad
2  Prabhas   46       Hyedrabad
3       PK   47  Vishakhapatnam

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('customers-100.csv')
print(df.head(10))
print(df.columns)

   Index      Customer Id First Name  Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl     Baxter   
1      2  1Ef7b82A4CAAD10    Preston     Lozano   
2      3  6F94879bDAfE5a6        Roy      Berry   
3      4  5Cef8BFA16c5e3c      Linda      Olsen   
4      5  053d585Ab6b3159     Joanna     Bender   
5      6  2d08FB17EE273F4      Aimee      Downs   
6      7  EA4d384DfDbBf77     Darren       Peck   
7      8  0e04AFde9f225dE      Brett     Mullen   
8      9  C2dE4dEEc489ae0     Sheryl     Meyers   
9     10  8C2811a503C7c5a   Michelle  Gallagher   

                           Company               City  \
0                  Rasmussen Group       East Leonard   
1                      Vega-Gentry  East Jimmychester   
2                    Murillo-Perry      Isabelborough   
3  Dominguez, Mcmillan and Donovan         Bensonview   
4         Martin, Lang and Andrade     West Priscilla   
5                     Steele Group      Chavezborough   
6     Lester, Woodard and Mitchell     

In [ ]:
# Handaling missing values
df.isnull().sum()

Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

In [ ]:
df.isnull().any()
# GIve does any column have missing values

Index                False
Customer Id          False
First Name           False
Last Name            False
Company              False
City                 False
Country              False
Phone 1              False
Phone 2              False
Email                False
Subscription Date    False
Website              False
dtype: bool

In [ ]:
df.fillna(0)
#if any where missing values present it will replace it by 0

Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...                ...   
95                        Carey LLC       East Richard   
96            Ware, Burns and Oneal       New Bradview   
97                    Schmitt-Jones         Ortegaland   
98               Fitzgerald-Harrell    Lake Elijahview   
99               Le, Nash and Cross          Judymouth   

                       Country                 Phone 1  \
0                        Chile            229.077.5154   
1                     Djibouti              5153435776   
2          Antigua and Barbuda         +1-539-402-0259   
3           Dominican Republic  001-808-617-6467x12895   
4   Slovakia (Slovak Republic)  001-234-203-0635x76146   
..                         ...                     ...   
95                      Guyana     (188)169-1674x58692   
96                   Sri Lanka         +1-846-706-2218   
97             Solomon Islands    +1-753-067-8419x7170   
98                       Aruba           (530)311-9786   
99                    Honduras           (753)813-6941   

                   Phone 2                           Email Subscription Date  \
0         397.884.0519x718        zunigavanessa@smith.info        2020-08-24   
1         686-620-1820x944                 vmata@colon.com        2021-04-23   
2      (496)978-3969x58947             beckycarr@hogan.com        2020-03-25   
3          +1-813-324-8756     stanleyblackwell@benson.org        2020-06-02   
4    001-199-446-3860x3486         colinalvarado@miles.net        2021-04-17   
..                     ...                             ...               ...   
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.3198               vkemp@ferrell.com        2021-07-10   
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18   
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11   
99            783.639.1472          colleen91@faulkner.biz        2020-03-11   

                              Website  
0          http://www.stephenson.com/  
1               http://www.hobbs.com/  
2            http://www.lawrence.com/  
3          http://www.good-lyons.com/  
4         https://goodwin-ingram.com/  
..                                ...  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/  

[100 rows x 12 columns]

In [46]:
df=pd.read_csv('sales_data.csv')
df.head()
df.columns

Index(['Transaction ID', 'Date', 'Product Category', 'Product Name',
       'Units Sold', 'Unit Price', 'Total Revenue', 'Region',
       'Payment Method'],
      dtype='object')

In [47]:
df.isnull().any()

Transaction ID      False
Date                False
Product Category    False
Product Name        False
Units Sold          False
Unit Price          False
Total Revenue       False
Region              False
Payment Method      False
dtype: bool

In [48]:
df['Sales_Fill_NA']=df['Total Revenue'].fillna(df['Total Revenue'].mean())

# Werever there is Nan value there it will replace with mean

In [49]:
df.head()

Transaction ID        Date Product Category             Product Name  \
0           10001  2024-01-01      Electronics            iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances         Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing         Levi's 501 Jeans   
3           10004  2024-01-04            Books        The Da Vinci Code   
4           10005  2024-01-05  Beauty Products  Neutrogena Skincare Set   

   Units Sold  Unit Price  Total Revenue         Region Payment Method  \
0           2      999.99        1999.98  North America    Credit Card   
1           1      499.99         499.99         Europe         PayPal   
2           3       69.99         209.97           Asia     Debit Card   
3           4       15.99          63.96  North America    Credit Card   
4           1       89.99          89.99         Europe         PayPal   

   Sales_Fill_NA  
0        1999.98  
1         499.99  
2         209.97  
3          63.96  
4          89.99

In [52]:
df=df.rename(columns={'Total Revenue':'Revenue'})
df

Transaction ID        Date Product Category  \
0             10001  2024-01-01      Electronics   
1             10002  2024-01-02  Home Appliances   
2             10003  2024-01-03         Clothing   
3             10004  2024-01-04            Books   
4             10005  2024-01-05  Beauty Products   
..              ...         ...              ...   
235           10236  2024-08-23  Home Appliances   
236           10237  2024-08-24         Clothing   
237           10238  2024-08-25            Books   
238           10239  2024-08-26  Beauty Products   
239           10240  2024-08-27           Sports   

                                        Product Name  Units Sold  Unit Price  \
0                                      iPhone 14 Pro           2      999.99   
1                                   Dyson V11 Vacuum           1      499.99   
2                                   Levi's 501 Jeans           3       69.99   
3                                  The Da Vinci Code           4       15.99   
4                            Neutrogena Skincare Set           1       89.99   
..                                               ...         ...         ...   
235  Nespresso Vertuo Next Coffee and Espresso Maker           1      159.99   
236                        Nike Air Force 1 Sneakers           3       90.00   
237           The Handmaid's Tale by Margaret Atwood           3       10.99   
238             Sunday Riley Luna Sleeping Night Oil           1       55.00   
239                       Yeti Rambler 20 oz Tumbler           2       29.99   

     Revenue         Region Payment Method  Sales_Fill_NA  
0    1999.98  North America    Credit Card        1999.98  
1     499.99         Europe         PayPal         499.99  
2     209.97           Asia     Debit Card         209.97  
3      63.96  North America    Credit Card          63.96  
4      89.99         Europe         PayPal          89.99  
..       ...            ...            ...            ...  
235   159.99         Europe         PayPal         159.99  
236   270.00           Asia     Debit Card         270.00  
237    32.97  North America    Credit Card          32.97  
238    55.00         Europe         PayPal          55.00  
239    59.98           Asia    Credit Card          59.98  

[240 rows x 10 columns]

In [53]:
df.head(10)

Transaction ID        Date Product Category                 Product Name  \
0           10001  2024-01-01      Electronics                iPhone 14 Pro   
1           10002  2024-01-02  Home Appliances             Dyson V11 Vacuum   
2           10003  2024-01-03         Clothing             Levi's 501 Jeans   
3           10004  2024-01-04            Books            The Da Vinci Code   
4           10005  2024-01-05  Beauty Products      Neutrogena Skincare Set   
5           10006  2024-01-06           Sports  Wilson Evolution Basketball   
6           10007  2024-01-07      Electronics          MacBook Pro 16-inch   
7           10008  2024-01-08  Home Appliances         Blueair Classic 480i   
8           10009  2024-01-09         Clothing             Nike Air Force 1   
9           10010  2024-01-10            Books        Dune by Frank Herbert   

   Units Sold  Unit Price  Revenue         Region Payment Method  \
0           2      999.99  1999.98  North America    Credit Card   
1           1      499.99   499.99         Europe         PayPal   
2           3       69.99   209.97           Asia     Debit Card   
3           4       15.99    63.96  North America    Credit Card   
4           1       89.99    89.99         Europe         PayPal   
5           5       29.99   149.95           Asia    Credit Card   
6           1     2499.99  2499.99  North America    Credit Card   
7           2      599.99  1199.98         Europe         PayPal   
8           6       89.99   539.94           Asia     Debit Card   
9           2       25.99    51.98  North America    Credit Card   

   Sales_Fill_NA  
0        1999.98  
1         499.99  
2         209.97  
3          63.96  
4          89.99  
5         149.95  
6        2499.99  
7        1199.98  
8         539.94  
9          51.98

In [54]:
# Data Aggregation and Grouping
# Finding the mean of the Unit Price according to the region

grouped_mean=df.groupby('Region')['Unit Price'].mean()
print(grouped_mean) 

Region
Asia             164.41025
Europe           190.90425
North America    353.87225
Name: Unit Price, dtype: float64


In [60]:
region_group=df.groupby(['Region','Product Name'])['Revenue'].sum()
print(region_group)

Region         Product Name                          
Asia           Adidas 3-Stripes Shorts                    149.95
               Adidas Essential Track Pants               134.97
               Adidas FIFA World Cup Football              89.97
               Adidas Originals Superstar Sneakers        319.96
               Adidas Originals Trefoil Hoodie            259.96
                                                          ...   
North America  The Sun Also Rises by Ernest Hemingway      35.97
               Think and Grow Rich by Napoleon Hill        29.97
               To Kill a Mockingbird by Harper Lee         59.96
               Where the Crawdads Sing by Delia Owens      75.96
               iPhone 14 Pro                             1999.98
Name: Revenue, Length: 233, dtype: float64


In [63]:
# Aggregating multiple functions
mult_funct=df.groupby('Region')['Revenue'].agg(['sum','count','mean'])
mult_funct

sum  count        mean
Region                                    
Asia           22455.45     80  280.693125
Europe         21268.06     80  265.850750
North America  36844.34     80  460.554250

In [65]:
df1=pd.DataFrame({
    'key':['a','b','c'],
    'value':[1,2,3,]
})
df2=pd.DataFrame({
    'key':['d','e','f'],
    'value':[11,12,13,]
})

In [66]:
df1

key  value
0   a      1
1   b      2
2   c      3

In [71]:
merged=pd.merge(df1,df2,on='key',how='outer')
print(merged)

  key  value_x  value_y
0   a      1.0      NaN
1   b      2.0      NaN
2   c      3.0      NaN
3   d      NaN     11.0
4   e      NaN     12.0
5   f      NaN     13.0
